/*

 BALL.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char ball[] =
{
  0x18,0x18,0x34,0x2C,0x72,0x4E,0xE1,0x9F,
  0xE1,0x9F,0x62,0x5E,0x24,0x3C,0x18,0x18
};

/* End of BALL.C */
