/*

 EXPORT.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char block[] =
{
  0x7F,0xFF,0xFF,0x80,0xFF,0x80,0xFF,0x80,
  0xFF,0x80,0xFF,0x80,0xFF,0x80,0x7F,0xFF,
  0xFE,0xFF,0xFF,0x01,0xFF,0x01,0xFF,0x01,
  0xFF,0x01,0xFF,0x01,0xFF,0x01,0xFE,0xFF
};

/* End of EXPORT.C */
