/*

 MENUBACK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Codigo\gbarcade\raw files\menu.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 3
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define boxWidth 20
#define boxHeight 18
#define boxBank 0

extern unsigned char box[];

/* End of MENUBACK.H */
