/*

 PADDLE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char paddle[] =
{
  0x7E,0x7E,0x81,0xFF,0x99,0xE7,0xA5,0xC3,
  0xA5,0xC3,0xA5,0xC3,0xA5,0xC3,0xA5,0xC3,
  0xA5,0xC3,0xA5,0xC3,0xA5,0xC3,0xA5,0xC3,
  0xA5,0xC3,0x99,0xE7,0x81,0xFF,0x7E,0x7E
};

/* End of PADDLE.C */
