/*

 PADDLEB.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char paddle[] =
{
  0x7F,0x7F,0x80,0xFF,0x9F,0xE0,0xA0,0xC0,
  0xA0,0xC0,0x9F,0xE0,0x80,0xFF,0x7F,0x7F,
  0xFE,0xFE,0x01,0xFF,0xF9,0x07,0x05,0x03,
  0x05,0x03,0xF9,0x07,0x01,0xFF,0xFE,0xFE
};

/* End of PADDLEB.C */
